hello_duck:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /data/projects/hello_duck/hello.duckdb
      threads: 4

pro:
  outputs:
    dev:
      type: duckdb
      path: /data/pro.duckdb
      threads: 1

    prod:
      type: duckdb
      path: /data/pro.raw.duckdb
      threads: 4

  target: dev
